apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dac3ey796-nodejs
  janus-idp.io/tekton: dac3ey796-nodejs
  backstage.io/kubernetes-id: dac3ey796-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dac3ey796-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
