apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dac3ey796-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dac3ey796-nodejs 
  name: dac3ey796-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dac3ey796-nodejs 
